import type { Metadata } from 'next';
import Link from 'next/link';
import { ArticleJsonLd } from '@/components/seo/JsonLd';

export const metadata: Metadata = {
  title: 'P/E Ratio Explained | FundersAI Learn',
  description: 'Understand the Price-to-Earnings ratio and how to use it when analyzing Indian stocks.',
  alternates: {
    canonical: 'https://www.fundersai.co.in/learn/pe-ratio',
  },
};

export default function PERatioPage() {
  return (
    <>
      <ArticleJsonLd
        title="P/E Ratio Explained"
        description="Understand the Price-to-Earnings ratio and how to use it when analyzing Indian stocks."
        slug="pe-ratio"
      />
      <article className="prose prose-invert prose-slate max-w-none">
      <div className="mb-8">
        <Link href="/learn" className="text-[#00FF9D] hover:underline text-sm font-medium">
          &larr; Back to Learning Hub
        </Link>
      </div>
      
      <h1 className="text-3xl md:text-4xl font-serif font-semibold tracking-tight text-white mb-6">
        P/E Ratio Explained
      </h1>
      
      <div className="text-slate-300 space-y-6 leading-relaxed">
        <p>
          The <strong>Price-to-Earnings (P/E) ratio</strong> is one of the most widely used metrics by investors to evaluate whether a stock is overvalued, undervalued, or fairly priced. 
        </p>

        <h2 className="text-2xl font-medium text-white mt-8 mb-4">How is the P/E Ratio calculated?</h2>
        <p>
          The formula is simple:
        </p>
        <div className="bg-white/[0.04] p-4 rounded-lg border border-white/10 font-mono text-center text-[#b3ffdb]">
          P/E Ratio = Market Price per Share / Earnings per Share (EPS)
        </div>
        <p>
          For example, if a company&apos;s stock is trading at ₹500 and its EPS over the last 12 months is ₹25, the P/E ratio would be 20. This means investors are willing to pay ₹20 for every ₹1 of earnings generated by the company.
        </p>

        <h2 className="text-2xl font-medium text-white mt-8 mb-4">What does a high or low P/E mean?</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>High P/E:</strong> Often indicates that investors expect high earnings growth in the future. However, it can also mean the stock is overvalued. Growth stocks typically have higher P/E ratios.</li>
          <li><strong>Low P/E:</strong> Might suggest that the stock is undervalued, or that the company is experiencing difficulties. Value investors often look for low P/E stocks.</li>
        </ul>

        <h2 className="text-2xl font-medium text-white mt-8 mb-4">Context is Key</h2>
        <p>
          A P/E ratio should never be looked at in isolation. It is crucial to compare a company&apos;s P/E to:
        </p>
        <ol className="list-decimal pl-6 space-y-2">
          <li><strong>Industry Peers:</strong> A software company will naturally have a higher P/E than a steel manufacturing company.</li>
          <li><strong>Historical Averages:</strong> Compare the company&apos;s current P/E to its 3-year or 5-year average.</li>
        </ol>

        <div className="mt-12 p-6 rounded-2xl border border-[#00FF9D]/20 bg-[#00FF9D]/[0.05]">
          <h3 className="text-lg font-medium text-white mb-2">Analyze P/E Ratios with FundersAI</h3>
          <p className="text-sm text-slate-300 mb-4">
            Use FundersAI to instantly compare the P/E ratios of Indian stocks alongside their historical averages and sector peers.
          </p>
          <Link href="/dashboard" className="inline-flex items-center justify-center rounded-lg bg-[#00FF9D] px-6 py-2.5 text-sm font-semibold text-black hover:bg-[#00FF9D]/90 transition">
            Try it in the Dashboard
          </Link>
        </div>
      </div>
    </article>
    </>
  );
}
