import type { Metadata } from 'next';
import Link from 'next/link';
import { EcosystemHeader } from '@/components/ecosystem/EcosystemHeader';
import PublicFooter from '@/components/layout/PublicFooter';

export const metadata: Metadata = {
  title: 'Metric Formulas & Math | FundersAI Methodology',
  description:
    'Exact mathematical definitions and code formulas used by FundersAI to compute Sharpe Ratio, Sortino Ratio, Alpha, Beta, Max Drawdown, and CAGR.',
  keywords: [
    'Mutual fund metric formulas',
    'Sharpe ratio formula India mutual fund',
    'Beta calculation Nifty 50 benchmark',
    'FundersAI mathematical formulas',
  ],
  alternates: {
    canonical: 'https://www.fundersai.co.in/methodology/formulas',
  },
  openGraph: {
    images: ['/opengraph-image'],
    title: 'Metric Formulas & Math | FundersAI Methodology',
    description: 'Explore the exact quantitative math behind FundersAI metric calculations.',
    url: 'https://www.fundersai.co.in/methodology/formulas',
    siteName: 'FundersAI',
  },
};

const formulasList = [
  {
    name: 'Compound Annual Growth Rate (CAGR)',
    label: 'CAGR Formula',
    formula: 'CAGR = (NAV_end / NAV_start) ^ (1 / Years) - 1',
    desc: 'Calculated over exact 1-year, 3-year, and 5-year periods using historical daily NAV series from AMFI.',
  },
  {
    name: 'Sharpe Ratio',
    label: 'Sharpe Formula',
    formula: 'Sharpe = (Annualized Return - Risk Free Rate) / Annualized Standard Deviation',
    desc: 'Measures risk-adjusted performance per unit of total risk. Risk-free rate is set to the current RBI 91-day T-Bill yield (6.5%).',
  },
  {
    name: 'Sortino Ratio',
    label: 'Sortino Formula',
    formula: 'Sortino = (Annualized Return - Risk Free Rate) / Downside Deviation',
    desc: 'Evaluates risk-adjusted return relative exclusively to negative return periods (downside risk).',
  },
  {
    name: 'Beta (Market Sensitivity)',
    label: 'Beta Formula',
    formula: 'Beta = Covariance(Fund Returns, Benchmark Returns) / Variance(Benchmark Returns)',
    desc: 'Calculated against the scheme’s primary benchmark (e.g. Nifty 50 TRI or Nifty 500 TRI) using 36-month rolling monthly returns.',
  },
  {
    name: 'Jensen’s Alpha',
    label: 'Alpha Formula',
    formula: 'Alpha = Fund Return - [Risk Free Rate + Beta * (Benchmark Return - Risk Free Rate)]',
    desc: 'Quantifies benchmark outperformance generated by the fund manager after accounting for systematic market risk.',
  },
  {
    name: 'Maximum Drawdown',
    label: 'Max Drawdown Formula',
    formula: 'Max Drawdown = Min((NAV_t - Peak_t) / Peak_t)',
    desc: 'Measures the largest peak-to-trough drop in percentage over a 3-year historical window.',
  },
];

export default function MethodologyFormulasPage() {
  return (
    <div className="min-h-screen bg-[#070b12] text-[#dce8fa] flex flex-col selection:bg-blue-500/30">
      <EcosystemHeader />

      <main className="flex-1 max-w-[1200px] mx-auto px-4 sm:px-6 lg:px-8 pt-28 pb-20 w-full space-y-10">
        <div className="flex items-center gap-2 text-xs font-mono text-gray-400">
          <Link href="/methodology" className="hover:text-emerald-400">Methodology</Link>
          <span>/</span>
          <span className="text-cyan-400">02. Formulas &amp; Math</span>
        </div>

        <div className="space-y-4 max-w-3xl">
          <span className="text-xs font-mono font-bold uppercase tracking-wider text-cyan-400">Quantitative Standard</span>
          <h1 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight">Metric Formulas &amp; Mathematics</h1>
          <p className="text-sm text-gray-400 leading-relaxed">
            All financial ratios in FundersAI are computed in Python code using NumPy and Pandas from validated NAV histories.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {formulasList.map((f, idx) => (
            <div key={idx} className="p-6 rounded-2xl bg-gray-950/80 border border-gray-800 space-y-3">
              <span className="text-xs font-mono text-cyan-400 font-semibold">{f.name}</span>
              <div className="p-3 rounded-lg bg-gray-900 border border-gray-800 font-mono text-xs text-emerald-300">
                {f.formula}
              </div>
              <p className="text-xs text-gray-400 leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </main>

      <PublicFooter />
    </div>
  );
}
